# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca18e88a853a9a06401e6b6419c0982ac52ce4de4e3f53638aecbdc5f0055723a9e443b6072b3aefe9d3451e403c4d8a0714d623b6c5b876105c385113596d2c

test:
  secret_key_base: e4e48fddee217847700881f8f3d1e2fed50c7e083d8547ff1dba0ddc7a73227e36517682098614cb22709c719df57179107c5eaf390d88dc6e260e14cd3fe961

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
